namespace:
  name: sandbox
replicaCount: 1

image:
  repository: namtea3/techtrends
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi

containerPort: 3111

livenessProbe:
  path: /healthz
  port: 3111

readinessProbe:
  path: /healthz
  port: 3111

service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP