namespace:
  name: staging
replicaCount: 3

image:
  repository: namtea3/techtrends
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 300m
    memory: 90Mi
  limits:
    cpu: 500m
    memory: 128Mi

containerPort: 3111

livenessProbe:
  path: /healthz

readinessProbe:
  path: /healthz

service:
  port: 5111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP