namespace:
  name: prod
replicaCount: 5

image:
  repository: namtea3/techtrends
  tag: latest
  pullPolicy: Always

resources:
  requests:
    cpu: 350m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

containerPort: 3111

livenessProbe:
  path: /healthz

readinessProbe:
  path: /healthz

service:
  port: 7111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP